name: "[Demo] Run Scan Action"

on: [push, pull_request]

jobs:
  test-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        source: "alpine:latest"
        debug: true

  test-directory:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        source: "dir://tests/python"
        debug: true
